export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const FIRST_LOAD = 'FIRST_LOAD';
export const UPDATE_TIME = 'UPDATE_TIME';
export const UPDATE_TIME_NOTIF = 'UPDATE_TIME_NOTIF';
// home page
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';
// auth
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
// SMS
export const GET_DETAIL_SMS_BY_MSISDN = 'GET_DETAIL_SMS_BY_MSISDN';
export const VIEW_DETAIL_SMS_PAGE_UNLOADED = 'VIEW_DETAIL_SMS_PAGE_UNLOADED';
export const GET_REFERENCE_SMS_BY_MSISDN = 'GET_REFERENCE_SMS_BY_MSISDN';
export const UPDATE_DETAIL_SMS_PAGE_UNLOADED = 'UPDATE_DETAIL_SMS_PAGE_UNLOADED';
export const UPDATE_FIELD_SMS = 'UPDATE_FIELD_SMS';
export const UPDATE_SMS_REFERENCE = 'UPDATE_SMS_REFERENCE';

