export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const FIRST_LOAD = 'FIRST_LOAD';
export const UPDATE_TIME = 'UPDATE_TIME';
export const UPDATE_TIME_NOTIF = 'UPDATE_TIME_NOTIF';
// home page
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';
// auth
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
// ticket
export const TICKET_PAGE_UNLOADED = 'TICKET_PAGE_UNLOADED';
export const GET_TICKET = 'GET_TICKET';
export const GET_TICKET_BY_USER = 'GET_TICKET_BY_USER';
export const GET_TICKET_BY_ID = 'GET_TICKET_BY_ID';
export const INSERT_TICKET = 'INSERT_TICKET';
export const DELETE_TICKET_BY_ID = 'DELETE_TICKET_BY_ID';
export const SEARCH_TICKET = 'SEARCH_TICKET';
export const UPDATE_FIELD_TICKET = 'UPDATE_FIELD_TICKET';
export const UPDATE_SEARCH_TICKET = 'UPDATE_SEARCH_TICKET';
export const UPDATE_DOCUMENT_TICKET = 'UPDATE_DOCUMENT_TICKET';
export const UPDATE_DOCUMENT_EXECUTOR_TICKET = 'UPDATE_DOCUMENT_EXECUTOR_TICKET';
export const REMOVE_ALL_UPLOADED_DOCUMENTS = 'REMOVE_ALL_UPLOADED_DOCUMENTS';
export const VIEW_TICKET_PAGE_UNLOADED = 'VIEW_TICKET_PAGE_UNLOADED';
export const DELETE_TICKET_PAGE_UNLOADED = 'DELETE_TICKET_PAGE_UNLOADED';
export const INSERT_TICKET_LOADED = 'INSERT_TICKET_LOADED';
export const INSERT_TICKET_PAGE_UNLOADED = 'INSERT_TICKET_PAGE_UNLOADED';
export const REMOVE_SINGLE_DOCS = 'REMOVE_SINGLE_DOCS';
export const REMOVE_SINGLE_DOCS_EXECUTOR = 'REMOVE_SINGLE_DOCS_EXECUTOR';
export const EXCEED_UPLOAD_QUOTA = 'EXCEED_UPLOAD_QUOTA';
// UPDATE TICKET
export const UPDATE_TICKET_PAGE_UNLOADED = 'UPDATE_TICKET_PAGE_UNLOADED';
export const UPDATE_TICKET_LOADED = 'UPDATE_TICKET_LOADED';
export const UPDATE_TICKET = 'UPDATE_TICKET';
// APPROVER
export const REVIEW_TICKET_LOADED = 'REVIEW_TICKET_LOADED';
export const REJECT_TICKET = 'REJECT_TICKET';
export const APPROVE_TICKET = 'APPROVE_TICKET';
export const DONE_TICKET = 'DONE_TICKET';
// EXECUTOR
export const EXECUTOR_PAGE_LOADED = 'EXECUTOR_PAGE_LOADED';
export const EXECUTOR_REJECT_TICKET = 'EXECUTOR_REJECT_TICKET';
export const EXECUTOR_APPROVE_TICKET = 'EXECUTOR_APPROVE_TICKET';
export const EXECUTOR_FINISH_TICKET = 'EXECUTOR_FINISH_TICKET';
// USER
export const USER_PAGE_UNLOADED = 'USER_PAGE_UNLOADED';
export const GET_USER = 'GET_USER';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const INSERT_USER = 'INSERT_USER';
export const UPDATE_USER_BY_ID = 'UPDATE_USER_BY_ID';
export const DELETE_USER_BY_ID = 'DELETE_USER_BY_ID';
export const SEARCH_USER = 'SEARCH_USER';
export const UPDATE_FIELD_USER = 'UPDATE_FIELD_USER';
export const VIEW_USER_PAGE_UNLOADED = 'VIEW_USER_PAGE_UNLOADED';
export const DELETE_USER_PAGE_UNLOADED = 'DELETE_USER_PAGE_UNLOADED';
export const INSERT_USER_PAGE_UNLOADED = 'INSERT_USER_PAGE_UNLOADED';
export const UPDATE_USER_PAGE_UNLOADED = 'INSERT_USER_PAGE_UNLOADED';
export const UPDATE_USER_PAGE_LOADED = 'UPDATE_USER_PAGE_LOADED';
